### PR TITLE
fix platformio_upload.py for SPIFFS

### PR DESCRIPTION
**Pull request by marcelrv**
Allows the script to upload files system images

### CODE REVIEW

**Review by lostMia — APPROVED** [review]
Works perfectly for me!

**Comment by freman** [comment]
Might I suggest a slightly different approach.

I'm not sure when this became a default but my envs all have "Upload Filesystem Image OTA" as a task now, this task target is called "uploadfsota" - this would seem to work with that configuration regardless of if it's spiffs or littlefs

```
        urlMode = "fs" if str(target[0]) == "uploadfsota" else "fr"

        # Führe die GET-Anfrage aus
        start_url = f"{upload_url}/ota/start?mode={urlMode}&hash={md5}"
```

**Comment by marcelrv** [comment]
> Might I suggest a slightly different approach.
> 
> I'm not sure when this became a default but my envs all have "Upload Filesystem Image OTA" as a task now, this task target is called "uploadfsota" - this would seem to work with that configuration regardless of if it's spiffs or littlefs
> 
> ```
>         urlMode = "fs" if str(target[0]) == "uploadfsota" else "fr"
> 
>         # Führe die GET-Anfrage aus
>         start_url = f"{upload_url}/ota/start?mode={urlMode}&hash={md5}"
> ```

yes, that would work, but indeed I did not chose that way as there are 2 filesystem uploads. 
The non-ota one does not work if the custom script is there. Hence by using the file name based approach both filesystem uploads are working.

**Comment by freman** [comment]
oh, I didn't encounter that, I keep my ota and non-ota in seperate envs.

**Pull request merged**
