### PR TITLE
Enable Async on RP2040

### PR DESCRIPTION
**Pull request by DoomHammer**

### CODE REVIEW

**Comment by ayushsharma82** [comment]
Thanks for the PR @DoomHammer !  I'll soon review and merge it for next release.

**Comment by mathieucarbou** [comment]
@DoomHammer : FYI I am maintaining a fork of ESPAsyncWebServer (https://github.com/mathieucarbou/ESPAsyncWebServer) which is used in many projects / lot of deployments.

I saw this PR, but until there is a valid AsyncTCP lib for RPI, it won't be possible to add support for RPI inside.

The Async lib (https://github.com/khoih-prog/AsyncTCP_RP2040W) used as dependency is archived and not maintained. The code greatly differ from the original ESPAsyncTCP (this is not even a fork), and has been completely renamed / restructured / refactored and reformatted. So it's not even possible to get a diff out of it and reapply it to a fork of ESPAsyncTCP.

ESPAsyncTCP and ESP8266 in general are / will be in the same boat...

**Comment by DoomHammer** [comment]
What do you mean, @mathieucarbou ? I've used this fork: https://github.com/skilau/ESPAsyncWebServer with some additional changes and I was generally satisfied with it.

**Comment by mathieucarbou** [comment]
> What do you mean, @mathieucarbou ? I've used this fork: https://github.com/skilau/ESPAsyncWebServer with some additional changes and I was generally satisfied with it.

ESPAsyncWebServer has some dependencies, which have also been ported. Look at the source code and project descriptors ;-)

The problem is that both the fork you use plus its dependencies are 1) not maintained and/or 2) archived, which means the developer specifically doesn't want anybody to use the dependencies anymore, whatever his reasons.

To have this  project work on rpi you need all dependencies to work and be ported to rpi and also be maintained, released, etc.

Other option is to takeover his work and support it.

But who will do that ?
Only someone heavily working on rpi could...

**Comment by ayushsharma82** [comment]
No worries. I'll list different dependencies in docs.

**Pull request merged**
